version: "3"
name: "eventhubs-emulator-with-containerized-app"
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    network_mode: host

  emulator:
    image: mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest
    volumes:
      - "./Config.json:/Eventhubs_Emulator/ConfigFiles/Config.json"
    environment:
      BLOB_SERVER: azurite
      METADATA_SERVER: azurite
      ACCEPT_EULA: "N"
    network_mode: host
    depends_on:
      - azurite

  sample-containerized-app:
    image: sample_app:latest
    network_mode: host
    depends_on:
      - emulator