spring:
  cloud:
    azure:
      eventhubs:
        connection-string: Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;
        storage:
          blob:
            connection-string: UseDevelopmentStorage=true
    function:
      definition: consume;supply
    stream:
      bindings:
        consume-in-0:
          destination: eh1
          group: $default
        supply-out-0:
          destination: eh1
      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
      default:
        producer:
          errorChannelEnabled: true
      poller:
        initial-delay: 0
        fixed-delay: 1000
